name: Call helloworld.ps1
on:
  workflow_dispatch:
  inputs:
      in_one:
        required: true
        type: string
env:
  PS_SOURCE_URL: "https://raw.githubusercontent.com/jsorling/miscscripts/main/github/actions"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CallHello
      run: '& iex ((New-Object System.Net.WebClient).DownloadString("$env:PS_SOURCE_URL/helloworld.ps1"))'
      shell: pwsh
